spring:
  application:
    name: trello-app
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/trello_app
    username: postgres
    password: bekberov
    hikari:
      maximum-pool-size: 50
  flyway:
        enabled: true
        validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8888
  error:
    include-message: always
    include-exception: true



