ALTER TABLE card_list ALTER COLUMN updated_by  DROP NOT NULL;
ALTER TABLE card ALTER COLUMN updated_by  DROP NOT NULL;
ALTER TABLE comment ALTER COLUMN updated_by  DROP NOT NULL;
ALTER TABLE attachment ALTER COLUMN updated_by  DROP NOT NULL;
ALTER TABLE reminder ALTER COLUMN updated_by  DROP NOT NULL;